//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int idCar { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public System.DateTime YearOfIssue { get; set; }
        public string Mileage { get; set; }
        public Nullable<int> IdDrive { get; set; }
        public Nullable<int> IdBody { get; set; }
        public Nullable<int> IdEng { get; set; }
        public string SizeOfWheel { get; set; }
    
        public virtual TypeOfBody TypeOfBody { get; set; }
        public virtual TypeOfDrive TypeOfDrive { get; set; }
        public virtual TypeOfEng TypeOfEng { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
